# Generated by Django 3.0.8 on 2020-07-27 16:22

import accounts.manager
import datetime
import django.contrib.auth.models
from django.db import migrations, models
import django.utils.timezone
import utils.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email_address')),
                ('social', models.CharField(blank=True, choices=[('KAKAO', 'kakao'), ('NAVER', 'naver'), ('APPLE', 'apple'), ('NONE', 'none')], default='NONE', max_length=20, null=True)),
                ('nickname', models.CharField(default='', max_length=30)),
                ('birth_day', models.DateField(default=datetime.date(1900, 1, 1))),
                ('profile', models.ImageField(blank=True, null=True, upload_to=utils.utils.create_upload_path)),
                ('bio', models.TextField(blank=True, max_length=300, null=True)),
                ('created_date', models.DateField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('object', accounts.manager.UserManager()),
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
